from enum import Enum

class EventType(str, Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    SYSTEM_DOWN = "SYSTEM_DOWN"
    HIGH_CPU_USAGE = "HIGH_CPU_USAGE"
    PORT_SCAN_DETECTED = "PORT_SCAN_DETECTED"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"